### ISSUE TITLE
slf4j dependency unaccounted for in pom.xml

### ISSUE THREAD

**Issue by pfaucon** [bioinform/longislnd#33]
running on Ubuntu 14.04.  This dependency seems to be unmet, when running the data simulation after fresh install I get the error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

it looks like it was previously a dependency but was removed.

**Comment by bayolau** [comment]
Dear @pfaucon , thank you for your interest in LongISLND. Just to get more information, is the binary release being used or are we building from the source code? What is the java and jdk version for example `java -version`?

**Comment by pfaucon** [comment]
@bayolau I ended up using the binary release version, but the problem I had was with building from source.  I'll update with java version in the morning when I'm in the lab.

**Comment by pfaucon** [comment]
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by bayolau** [comment]
dear @pfaucon . Thank you for pointing this out. Please check if the `master` branch works for you now.

**Comment by bayolau** [comment]
@pfaucon I'll close this for now, please feel reach out if there are other problems.
