### ISSUE TITLE
Assume yes in installation scripts

### ISSUE THREAD

**Issue by yoann-dufresne** [bioinform/longislnd#39]
For the bug that I raised [here](https://github.com/bioinform/longislnd/issues/38), I am trying to reproduce it within a singularity.
However, the execution of the script "linux_build.sh" need to answer "yes" to a license question. This answer is not possible from the singularity and the script assume "No".

So, should it be possible to add an option "-y" to the script (like for "apt upgrade") that will automatically trigger the Yes ?

**Comment by bayolau** [comment]
this is working as intended, such that the user won't blindly agree to licenses. User is welcomed to modify the script locally.

**Comment by yoann-dufresne** [comment]
I will do that to compile singularity images for clusters.

Thanks
